//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTFAK.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CTFAK.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] Active {
            get {
                object obj = ResourceManager.GetObject("Active", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] Active_Picture {
            get {
                object obj = ResourceManager.GetObject("Active_Picture", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] ActiveSystemBox {
            get {
                object obj = ResourceManager.GetObject("ActiveSystemBox", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] Backdrop {
            get {
                object obj = ResourceManager.GetObject("Backdrop", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] Button {
            get {
                object obj = ResourceManager.GetObject("Button", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] CalcRect {
            get {
                object obj = ResourceManager.GetObject("CalcRect", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] ComboBox {
            get {
                object obj = ResourceManager.GetObject("ComboBox", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] Counter {
            get {
                object obj = ResourceManager.GetObject("Counter", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] DateAndTime {
            get {
                object obj = ResourceManager.GetObject("DateAndTime", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] EasyScrollbar {
            get {
                object obj = ResourceManager.GetObject("EasyScrollbar", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] EditBoxSel {
            get {
                object obj = ResourceManager.GetObject("EditBoxSel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] EEEditbox {
            get {
                object obj = ResourceManager.GetObject("EEEditbox", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] EmptyIcon {
            get {
                object obj = ResourceManager.GetObject("EmptyIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] ExecuteInConsole {
            get {
                object obj = ResourceManager.GetObject("ExecuteInConsole", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] File {
            get {
                object obj = ResourceManager.GetObject("File", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] FileFolderObject {
            get {
                object obj = ResourceManager.GetObject("FileFolderObject", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] FontEmbedObject {
            get {
                object obj = ResourceManager.GetObject("FontEmbedObject", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] Formatted_Text {
            get {
                object obj = ResourceManager.GetObject("Formatted_Text", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] Frrr {
            get {
                object obj = ResourceManager.GetObject("Frrr", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] IIF {
            get {
                object obj = ResourceManager.GetObject("IIF", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] Ini {
            get {
                object obj = ResourceManager.GetObject("Ini", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] IniPLUS {
            get {
                object obj = ResourceManager.GetObject("IniPLUS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] InputObject {
            get {
                object obj = ResourceManager.GetObject("InputObject", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] InternalListObject {
            get {
                object obj = ResourceManager.GetObject("InternalListObject", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] List {
            get {
                object obj = ResourceManager.GetObject("List", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] Lives {
            get {
                object obj = ResourceManager.GetObject("Lives", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] ObjResize {
            get {
                object obj = ResourceManager.GetObject("ObjResize", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] Perspective {
            get {
                object obj = ResourceManager.GetObject("Perspective", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] PopupMenu {
            get {
                object obj = ResourceManager.GetObject("PopupMenu", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] PopupMessageobject2 {
            get {
                object obj = ResourceManager.GetObject("PopupMessageobject2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] QandA {
            get {
                object obj = ResourceManager.GetObject("QandA", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] Score {
            get {
                object obj = ResourceManager.GetObject("Score", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] String {
            get {
                object obj = ResourceManager.GetObject("String", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] StringReplace {
            get {
                object obj = ResourceManager.GetObject("StringReplace", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] SubApp {
            get {
                object obj = ResourceManager.GetObject("SubApp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] TreeControl {
            get {
                object obj = ResourceManager.GetObject("TreeControl", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] WindowControl {
            get {
                object obj = ResourceManager.GetObject("WindowControl", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] XLua {
            get {
                object obj = ResourceManager.GetObject("XLua", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
